#ifndef I2C_H
#define I2C_H

/* This file is generated by STM32CubeIDE when you add I2C1
 * as a peripheral. It is included here as a stub so the
 * driver files compile correctly.
 *
 * In STM32CubeIDE:
 *   1. Open your .ioc file
 *   2. Connectivity -> I2C1 -> Mode: I2C
 *   3. In Parameter Settings set Speed Mode: Fast Mode (400 kHz)
 *   4. Pin & Peripherals will show PB8=I2C1_SCL, PB9=I2C1_SDA
 *      (these are the physical pins 46 and 47 on the WB50CGU5)
 *   5. Generate code - this creates i2c.h and i2c.c with
 *      hi2c1 declared and MX_I2C1_Init() defined.
 *
 * Do not edit this stub - use the CubeIDE-generated version.
 */

#include "stm32wbxx_hal.h"

extern I2C_HandleTypeDef hi2c1;

void MX_I2C1_Init(void);

#endif /* I2C_H */
